version: '3.8'

services:
    app:
        build: .
        container_name: app
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - DB_HOST=db
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=root
            - DB_CONNECTION=mysql
            - QUEUE_CONNECTION=database
            - DB_QUEUE_CONNECTION=mysql
        volumes:
            - .:/app:cached
        working_dir: /app
        depends_on:
            - db

    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "8000:80"
        volumes:
            - .:/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: mysql-db
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"

volumes:
    db_data:
